development:
  secret_key_base:
  '85b924d099bbf51735127540446be03a337008e067ff536feef288b029c591c4004f77bce552593f
9f1135dc6d4ab0be30afe70448e3d09d0cc94b267c6c29dd
'
 
test:
  secret_key_base:
  '85b924d099bbf51735127540446be03a337008e067ff536feef288b029c591c4004f77bce552593f
9f1135dc6d4ab0be30afe70448e3d09d0cc94b267c6c29dd
'
 
production:
  secret_key_base:
  require 'securerandom'

def secure_token
  token_file = Rails.root.join('.secret')
  if File.exist?(token_file)
    # Use the existing token.
    File.read(token_file).chomp
  else
    # Generate a new token and store it in token_file.
    token = SecureRandom.hex(64)
    File.write(token_file, token)
    token
  end
end

SampleApp::Application.config.secret_key_base = secure_token